./build/Garnet_standalone/gem5.opt configs/example/garnet_synth_traffic.py \
--network=garnet2.0 \
--num-cpus=16 \
--num-dirs=16 \
--topology=Mesh_XY \
--mesh-rows=4 \
--sim-cycles=1000 \
--inj-vnet=2 \
--injectionrate=0.02 \
--synthetic=uniform_random \
--routing-algorithm=xy \
--if_routerless=0 \
--link_width_bits=128